from censo.models import *
from django.contrib import admin

admin.site.register(Occupation)
admin.site.register(Commune)
admin.site.register(Region)
admin.site.register(Cuerpo)
admin.site.register(Company)
admin.site.register(UserProfile)
admin.site.register(Province)
admin.site.register(InternetProvider)
admin.site.register(Speciality)
admin.site.register(VolunteerData)
admin.site.register(InfrastructureCompanyData)
admin.site.register(BuildingMaterialType)
admin.site.register(PropertyTitleType)
admin.site.register(CompanyOtherOfficial)
admin.site.register(CuerpoAlarmCentralData)
admin.site.register(PortadaCompanyData)
admin.site.register(PortadaCuerpoData)
admin.site.register(AccountingSystem)
admin.site.register(VHF)
admin.site.register(OperatingSystem)
admin.site.register(OriginSystem)
admin.site.register(CodedAlarmType)
admin.site.register(CodedKeysType)
admin.site.register(PortableBrand)
admin.site.register(PotencyRange)
admin.site.register(Condition)
admin.site.register(IncorporationStatus)
admin.site.register(Color)
admin.site.register(TransmissionType)
admin.site.register(MotorType)
admin.site.register(VehicleProcedence)
admin.site.register(VehicleRegistrationStatus)
admin.site.register(VehicleCheckupStatus)
admin.site.register(FireEngineCamivaModel)


