from speciality import Speciality
from role import Role
from occupation import Occupation
from commune import Commune
from region import Region
from cuerpo import Cuerpo
from volunteer_data import VolunteerData
from company import Company
from user_profile import UserProfile
from user_has_role import UserHasRole
from province import Province
from internet_provider import InternetProvider
from infrastructure_company_data import InfrastructureCompanyData
from building_material_type import BuildingMaterialType
from property_title_type import PropertyTitleType
from minor_material_company_data import MinorMaterialCompanyData
