from speciality import Speciality
from role import Role
from occupation import Occupation
from commune import Commune
from region import Region
from cuerpo import Cuerpo
from company import Company
from user_profile import UserProfile
from user_has_role import UserHasRole
from province import Province
